# Generated by Django 5.2.14 on 2026-05-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_availabilityslot_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
