service: email-service

provider:
  name: aws
  runtime: python3.12

  environment:
  GMAIL_EMAIL: yourgmail@gmail.com
  GMAIL_APP_PASSWORD: your_app_password

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.send_email

    events:
      - http:
          path: send-email
          method: post

